// Generated by akan-native from akan-native.config and the .env files (ENV-7). Do not edit: every build rewrites it.
// Key names only; the values stay in those files.
export {};

declare module "@akanjs/native/core" {
  interface AkanNativeEnv {
    /** .env, .env.development, .env.development.android */
    readonly PUBLIC_API_URL: string;
    /** akan-native.config, .env, akan-native.config (android) */
    readonly PUBLIC_GREETING: string;
  }
}
