// Writes packages/core/contract.json into the four host languages (docs/architecture.md §5):
//   bun scripts/contract.ts          write the generated files
//   bun scripts/contract.ts --check  exit 1 when one is stale (packages/core/test/contract.test.ts does the same)
// Only tables and constants are generated. The algorithms that use them are written per language
// and checked by the shared vectors (packages/core/vectors), because the bugs they catch come
// from each language's own libraries, which generated code would inherit as well.

import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const REPO = resolve(import.meta.dir, "..");

interface IdSpec {
  chars: string;
  min: number;
  max: number;
  first?: string;
  notFirst?: string;
  extChars?: string;
  extMax?: number;
}

interface Contract {
  errorCodes: string[];
  mime: Record<string, string>;
  mimeUtf8: { types: string[] };
  ids: { fileRef: IdSpec; bundle: IdSpec; document: IdSpec; name: IdSpec };
  schemes: { external: string[]; frames: string[]; neverExternal: string[] };
  routes: { root: string; init: string; ipc: string; hello: string; file: string };
  initPrefix: string;
  initSuffix: string;
  maxRangeBytes: number;
  externalOpensPerSecond: number;
  maxRetainedEvents: number;
}

/** "A-Za-z0-9_-" → every character it names, in order ("-" at the end is itself). */
export function expandChars(spec: string): string {
  let out = "";
  for (let i = 0; i < spec.length; i++) {
    if (spec[i + 1] === "-" && i + 2 < spec.length) {
      for (let c = spec.charCodeAt(i); c <= spec.charCodeAt(i + 2); c++) out += String.fromCharCode(c);
      i += 2;
    } else out += spec[i];
  }
  return out;
}

const HEADER = "Generated by scripts/contract.ts from packages/core/contract.json. Do not edit.";

const ts = (c: Contract, ids: [string, IdSpec][]) => {
  const q = (s: string) => JSON.stringify(s);
  const lines = [
    `// ${HEADER}`,
    "",
    `export const ERROR_CODES = [${c.errorCodes.map(q).join(", ")}] as const;`,
    "",
    "/** File name extension → MIME type (assets and FileRefs). */",
    `export const MIME: Readonly<Record<string, string>> = {`,
    ...Object.entries(c.mime).map(([k, v]) => `  ${/^[a-z]\w*$/.test(k) ? k : q(k)}: ${q(v)},`),
    "};",
    "",
    "/** Besides text/*, the asset types served with charset=utf-8. */",
    `export const MIME_UTF8: readonly string[] = [${c.mimeUtf8.types.map(q).join(", ")}];`,
    "",
    "/** An id grammar: allowed characters, length, and an optional extension after the first dot. */",
    "export interface IdSpec {",
    "  chars: string;",
    "  first: string;",
    "  notFirst: string;",
    "  min: number;",
    "  max: number;",
    "  extChars: string;",
    "  extMax: number;",
    "}",
    "",
    ...ids.map(
      ([name, s]) =>
        `export const ID_${name.replace(/[A-Z]/g, (m) => `_${m}`).toUpperCase()}: IdSpec = { chars: ${q(expandChars(s.chars))}, first: ${q(expandChars(s.first ?? ""))}, notFirst: ${q(s.notFirst ?? "")}, min: ${s.min}, max: ${s.max}, extChars: ${q(expandChars(s.extChars ?? ""))}, extMax: ${s.extMax ?? 0} };`,
    ),
    "",
    `export const EXTERNAL_SCHEMES: readonly string[] = [${c.schemes.external.map(q).join(", ")}];`,
    `export const FRAME_SCHEMES: readonly string[] = [${c.schemes.frames.map(q).join(", ")}];`,
    "/** Schemes an app can never add to the external list. */",
    `export const NEVER_EXTERNAL_SCHEMES: readonly string[] = [${c.schemes.neverExternal.map(q).join(", ")}];`,
    "",
    `export const ROUTES = { root: ${q(c.routes.root)}, init: ${q(c.routes.init)}, ipc: ${q(c.routes.ipc)}, hello: ${q(c.routes.hello)}, file: ${q(c.routes.file)} } as const;`,
    "",
    `export const INIT_PREFIX = ${q(c.initPrefix)};`,
    `export const INIT_SUFFIX = ${q(c.initSuffix)};`,
    `export const MAX_RANGE_BYTES = ${c.maxRangeBytes};`,
    `export const EXTERNAL_OPENS_PER_SECOND = ${c.externalOpensPerSecond};`,
    `export const MAX_RETAINED_EVENTS = ${c.maxRetainedEvents};`,
    "",
  ];
  return lines.join("\n");
};

/** A string literal for Rust, Swift or Kotlin (Kotlin also escapes "$"). */
const lit = (s: string, kotlin = false) =>
  `"${s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\$/g, kotlin ? "\\$" : "$")}"`;

const rust = (c: Contract, ids: [string, IdSpec][]) => {
  const q = (s: string) => lit(s);
  return [
    `//! ${HEADER}`,
    "#![allow(dead_code)]",
    "",
    `pub const ERROR_CODES: &[&str] = &[${c.errorCodes.map(q).join(", ")}];`,
    "",
    "/// File name extension → MIME type (assets and FileRefs).",
    "pub const MIME: &[(&str, &str)] = &[",
    ...Object.entries(c.mime).map(([k, v]) => `  (${q(k)}, ${q(v)}),`),
    "];",
    "",
    "/// Besides text/*, the asset types served with charset=utf-8.",
    `pub const MIME_UTF8: &[&str] = &[${c.mimeUtf8.types.map(q).join(", ")}];`,
    "",
    "/// An id grammar: allowed characters, length, and an optional extension after the first dot.",
    "pub struct IdSpec {",
    "  pub chars: &'static str,",
    "  pub first: &'static str,",
    "  pub not_first: &'static str,",
    "  pub min: usize,",
    "  pub max: usize,",
    "  pub ext_chars: &'static str,",
    "  pub ext_max: usize,",
    "}",
    "",
    ...ids.map(
      ([name, s]) =>
        `pub const ID_${name.replace(/[A-Z]/g, (m) => `_${m}`).toUpperCase()}: IdSpec = IdSpec { chars: ${q(expandChars(s.chars))}, first: ${q(expandChars(s.first ?? ""))}, not_first: ${q(s.notFirst ?? "")}, min: ${s.min}, max: ${s.max}, ext_chars: ${q(expandChars(s.extChars ?? ""))}, ext_max: ${s.extMax ?? 0} };`,
    ),
    "",
    `pub const EXTERNAL_SCHEMES: &[&str] = &[${c.schemes.external.map(q).join(", ")}];`,
    `pub const FRAME_SCHEMES: &[&str] = &[${c.schemes.frames.map(q).join(", ")}];`,
    "/// Schemes an app can never add to the external list.",
    `pub const NEVER_EXTERNAL_SCHEMES: &[&str] = &[${c.schemes.neverExternal.map(q).join(", ")}];`,
    "",
    `pub const ROUTE_ROOT: &str = ${q(c.routes.root)};`,
    `pub const ROUTE_INIT: &str = ${q(c.routes.init)};`,
    `pub const ROUTE_IPC: &str = ${q(c.routes.ipc)};`,
    `pub const ROUTE_HELLO: &str = ${q(c.routes.hello)};`,
    `pub const ROUTE_FILE: &str = ${q(c.routes.file)};`,
    "",
    `pub const INIT_PREFIX: &str = ${q(c.initPrefix)};`,
    `pub const INIT_SUFFIX: &str = ${q(c.initSuffix)};`,
    `pub const MAX_RANGE_BYTES: usize = ${c.maxRangeBytes};`,
    `pub const EXTERNAL_OPENS_PER_SECOND: u32 = ${c.externalOpensPerSecond};`,
    `pub const MAX_RETAINED_EVENTS: usize = ${c.maxRetainedEvents};`,
    "",
  ].join("\n");
};

const swift = (c: Contract, ids: [string, IdSpec][]) => {
  const q = (s: string) => lit(s);
  return [
    `// ${HEADER}`,
    "",
    "/// An id grammar: allowed characters, length, and an optional extension after the first dot.",
    "struct AkanNativeIdSpec: Sendable {",
    "    let chars: String",
    "    let first: String",
    "    let notFirst: String",
    "    let min: Int",
    "    let max: Int",
    "    let extChars: String",
    "    let extMax: Int",
    "}",
    "",
    "enum AkanNativeContract {",
    `    static let errorCodes: [String] = [${c.errorCodes.map(q).join(", ")}]`,
    "",
    "    /// File name extension → MIME type (assets and FileRefs).",
    "    static let mime: [String: String] = [",
    ...Object.entries(c.mime).map(([k, v]) => `        ${q(k)}: ${q(v)},`),
    "    ]",
    "",
    "    /// Besides text/*, the asset types served with charset=utf-8.",
    `    static let mimeUtf8: Set<String> = [${c.mimeUtf8.types.map(q).join(", ")}]`,
    "",
    ...ids.map(
      ([name, s]) =>
        `    static let id${name[0]!.toUpperCase()}${name.slice(1)} = AkanNativeIdSpec(chars: ${q(expandChars(s.chars))}, first: ${q(expandChars(s.first ?? ""))}, notFirst: ${q(s.notFirst ?? "")}, min: ${s.min}, max: ${s.max}, extChars: ${q(expandChars(s.extChars ?? ""))}, extMax: ${s.extMax ?? 0})`,
    ),
    "",
    `    static let externalSchemes: [String] = [${c.schemes.external.map(q).join(", ")}]`,
    `    static let frameSchemes: [String] = [${c.schemes.frames.map(q).join(", ")}]`,
    "    /// Schemes an app can never add to the external list.",
    `    static let neverExternalSchemes: [String] = [${c.schemes.neverExternal.map(q).join(", ")}]`,
    "",
    `    static let routeRoot = ${q(c.routes.root)}`,
    `    static let routeInit = ${q(c.routes.init)}`,
    `    static let routeIpc = ${q(c.routes.ipc)}`,
    `    static let routeHello = ${q(c.routes.hello)}`,
    `    static let routeFile = ${q(c.routes.file)}`,
    "",
    `    static let initPrefix = ${q(c.initPrefix)}`,
    `    static let initSuffix = ${q(c.initSuffix)}`,
    `    static let maxRangeBytes = ${c.maxRangeBytes}`,
    `    static let externalOpensPerSecond = ${c.externalOpensPerSecond}`,
    `    static let maxRetainedEvents = ${c.maxRetainedEvents}`,
    "}",
    "",
  ].join("\n");
};

const kotlin = (c: Contract, ids: [string, IdSpec][]) => {
  const q = (s: string) => lit(s, true);
  return [
    `// ${HEADER}`,
    "package com.akanjs.runtime",
    "",
    "/** An id grammar: allowed characters, length, and an optional extension after the first dot. */",
    "class AkanNativeIdSpec(val chars: String, val first: String, val notFirst: String, val min: Int, val max: Int, val extChars: String, val extMax: Int)",
    "",
    "object AkanNativeContract {",
    `    val ERROR_CODES = listOf(${c.errorCodes.map(q).join(", ")})`,
    "",
    "    /** File name extension → MIME type (assets and FileRefs). */",
    "    val MIME = mapOf(",
    ...Object.entries(c.mime).map(([k, v]) => `        ${q(k)} to ${q(v)},`),
    "    )",
    "",
    "    /** Besides the text types, the asset types served with charset=utf-8. */",
    `    val MIME_UTF8 = setOf(${c.mimeUtf8.types.map(q).join(", ")})`,
    "",
    ...ids.map(
      ([name, s]) =>
        `    val ID_${name.replace(/[A-Z]/g, (m) => `_${m}`).toUpperCase()} = AkanNativeIdSpec(${q(expandChars(s.chars))}, ${q(expandChars(s.first ?? ""))}, ${q(s.notFirst ?? "")}, ${s.min}, ${s.max}, ${q(expandChars(s.extChars ?? ""))}, ${s.extMax ?? 0})`,
    ),
    "",
    `    val EXTERNAL_SCHEMES = listOf(${c.schemes.external.map(q).join(", ")})`,
    `    val FRAME_SCHEMES = listOf(${c.schemes.frames.map(q).join(", ")})`,
    "    /** Schemes an app can never add to the external list. */",
    `    val NEVER_EXTERNAL_SCHEMES = listOf(${c.schemes.neverExternal.map(q).join(", ")})`,
    "",
    `    const val ROUTE_ROOT = ${q(c.routes.root)}`,
    `    const val ROUTE_INIT = ${q(c.routes.init)}`,
    `    const val ROUTE_IPC = ${q(c.routes.ipc)}`,
    `    const val ROUTE_HELLO = ${q(c.routes.hello)}`,
    `    const val ROUTE_FILE = ${q(c.routes.file)}`,
    "",
    `    const val INIT_PREFIX = ${q(c.initPrefix)}`,
    `    const val INIT_SUFFIX = ${q(c.initSuffix)}`,
    `    const val MAX_RANGE_BYTES = ${c.maxRangeBytes}`,
    `    const val EXTERNAL_OPENS_PER_SECOND = ${c.externalOpensPerSecond}`,
    `    const val MAX_RETAINED_EVENTS = ${c.maxRetainedEvents}`,
    "}",
    "",
  ].join("\n");
};

/** Every generated file: repository path → content. */
export function render(): Record<string, string> {
  const c = JSON.parse(readFileSync(join(REPO, "packages/core/contract.json"), "utf8")) as Contract;
  const ids = Object.entries(c.ids).filter(([k]) => k !== "about") as [string, IdSpec][];
  return {
    "packages/core/src/contract.ts": ts(c, ids),
    "native/desktop/src/contract.rs": rust(c, ids),
    "native/ios/Sources/AkanNativeContract.swift": swift(c, ids),
    "native/android/src/com/akanjs/runtime/AkanNativeContract.kt": kotlin(c, ids),
  };
}

export function stale(): string[] {
  return Object.entries(render())
    .filter(([path, text]) => {
      try {
        return readFileSync(join(REPO, path), "utf8") !== text;
      } catch {
        return true;
      }
    })
    .map(([path]) => path);
}

if (import.meta.main) {
  if (process.argv.includes("--check")) {
    const old = stale();
    if (old.length) {
      console.error(`stale (run bun scripts/contract.ts): ${old.join(", ")}`);
      process.exit(1);
    }
  } else {
    for (const [path, text] of Object.entries(render())) writeFileSync(join(REPO, path), text);
    console.info("contract: wrote 4 files");
  }
}
