// Generated by scripts/contract.ts from packages/core/contract.json. Do not edit.
package com.akanjs.runtime

/** An id grammar: allowed characters, length, and an optional extension after the first dot. */
class AkanNativeIdSpec(val chars: String, val first: String, val notFirst: String, val min: Int, val max: Int, val extChars: String, val extMax: Int)

object AkanNativeContract {
    val ERROR_CODES = listOf("UNSUPPORTED", "PERMISSION_DENIED", "CANCELLED", "TIMEOUT", "INVALID_ARGS", "NOT_FOUND", "NOT_ALLOWED", "INTERNAL")

    /** File name extension → MIME type (assets and FileRefs). */
    val MIME = mapOf(
        "html" to "text/html",
        "htm" to "text/html",
        "js" to "text/javascript",
        "mjs" to "text/javascript",
        "css" to "text/css",
        "json" to "application/json",
        "map" to "application/json",
        "webmanifest" to "application/manifest+json",
        "txt" to "text/plain",
        "text" to "text/plain",
        "log" to "text/plain",
        "md" to "text/markdown",
        "csv" to "text/csv",
        "tsv" to "text/tab-separated-values",
        "xml" to "application/xml",
        "yaml" to "application/yaml",
        "yml" to "application/yaml",
        "ics" to "text/calendar",
        "vcf" to "text/vcard",
        "pdf" to "application/pdf",
        "rtf" to "application/rtf",
        "zip" to "application/zip",
        "gz" to "application/gzip",
        "tar" to "application/x-tar",
        "wasm" to "application/wasm",
        "epub" to "application/epub+zip",
        "doc" to "application/msword",
        "docx" to "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "xls" to "application/vnd.ms-excel",
        "xlsx" to "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "ppt" to "application/vnd.ms-powerpoint",
        "pptx" to "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "png" to "image/png",
        "jpg" to "image/jpeg",
        "jpeg" to "image/jpeg",
        "gif" to "image/gif",
        "webp" to "image/webp",
        "avif" to "image/avif",
        "heic" to "image/heic",
        "heif" to "image/heif",
        "bmp" to "image/bmp",
        "svg" to "image/svg+xml",
        "ico" to "image/x-icon",
        "tif" to "image/tiff",
        "tiff" to "image/tiff",
        "mp3" to "audio/mpeg",
        "m4a" to "audio/mp4",
        "aac" to "audio/aac",
        "wav" to "audio/wav",
        "ogg" to "audio/ogg",
        "flac" to "audio/flac",
        "mp4" to "video/mp4",
        "m4v" to "video/mp4",
        "mov" to "video/quicktime",
        "webm" to "video/webm",
        "ttf" to "font/ttf",
        "otf" to "font/otf",
        "woff" to "font/woff",
        "woff2" to "font/woff2",
        "glb" to "model/gltf-binary",
        "gltf" to "model/gltf+json",
    )

    /** Besides the text types, the asset types served with charset=utf-8. */
    val MIME_UTF8 = setOf("application/json", "application/manifest+json", "application/xml", "application/yaml", "image/svg+xml", "model/gltf+json")

    val ID_FILE_REF = AkanNativeIdSpec("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-", "", "", 1, 128, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789", 8)
    val ID_BUNDLE = AkanNativeIdSpec("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_.-", "", ".", 1, 80, "", 0)
    val ID_DOCUMENT = AkanNativeIdSpec("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-", "", "", 8, 64, "", 0)
    val ID_NAME = AkanNativeIdSpec("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_.-", "\$ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz", "", 1, 64, "", 0)

    val EXTERNAL_SCHEMES = listOf("http", "https", "mailto", "tel")
    val FRAME_SCHEMES = listOf("http", "https", "data", "blob", "about")
    /** Schemes an app can never add to the external list. */
    val NEVER_EXTERNAL_SCHEMES = listOf("javascript", "vbscript", "file", "data", "blob", "about", "content", "intent", "app")

    const val ROUTE_ROOT = "__akan_native"
    const val ROUTE_INIT = "init.js"
    const val ROUTE_IPC = "ipc"
    const val ROUTE_HELLO = "hello"
    const val ROUTE_FILE = "file"

    const val INIT_PREFIX = "window.__AKAN_NATIVE__=(function(o,b,e){for(var k in b)o[k]=b[k];o.env=e;return o})(window.__AKAN_NATIVE__||{},"
    const val INIT_SUFFIX = ");\n"
    const val MAX_RANGE_BYTES = 1024000
    const val EXTERNAL_OPENS_PER_SECOND = 1
    const val MAX_RETAINED_EVENTS = 16
}
