import {
  AGENT_BLOCK_END,
  AGENT_BLOCK_START,
  CLAUDE_COMMENT_RULE,
  readDevkitVersion,
  renderRecipeEntries,
  stampBlockVersion,
  upsertAgentBlock,
} from "@akanjs/devkit/agentsIndex";
import { AkanContextAnalyzer, type AkanWorkspaceContext } from "@akanjs/devkit/akanContext";
import { runner, type Workspace } from "@akanjs/devkit/commandDecorators";
import { AppExecutor, LibExecutor } from "@akanjs/devkit/executors";
import { Prompter } from "@akanjs/devkit/prompter";
import { collectRecipeSources, scanRecipes } from "@akanjs/devkit/recipeScanner";
import { Logger } from "akanjs/common";

type AgentTarget = "cursor" | "agents-md" | "claude";

const targetPaths: Record<AgentTarget, string> = {
  cursor: ".cursor/rules/akan.mdc",
  "agents-md": "AGENTS.md",
  claude: "CLAUDE.md",
};

// Reference samples scaffolded by `akan create-workspace`. They demonstrate the conventions but are not
// part of the product, so agents should remove them before building real features.
const SAMPLE_ARTIFACTS = [
  { probe: "lib/task/task.constant.ts", target: "lib/task", label: "sample database module" },
  { probe: "lib/_noti/noti.service.ts", target: "lib/_noti", label: "sample service module" },
  {
    probe: "lib/__scalar/workHistory/workHistory.dictionary.ts",
    target: "lib/__scalar/workHistory",
    label: "sample scalar module",
  },
  { probe: "page/task/_index.tsx", target: "page/task", label: "sample task pages" },
] as const;
const DEFAULT_INDEX_MARKER = "Akan.js template";

// Detect which scaffolded samples still exist so the guidance disappears once they are removed.
const renderSampleCleanup = async (workspace: Workspace, appNames: string[]) => {
  const items: string[] = [];
  for (const appName of appNames) {
    for (const artifact of SAMPLE_ARTIFACTS) {
      if (await workspace.exists(`apps/${appName}/${artifact.probe}`)) {
        items.push(
          `- \`apps/${appName}/${artifact.target}\` — ${artifact.label}; delete it once you no longer need the reference.`,
        );
      }
    }
    const indexPath = `apps/${appName}/page/_index.tsx`;
    if (await workspace.exists(indexPath)) {
      const content = await workspace.readFile(indexPath).catch(() => "");
      if (content.includes(DEFAULT_INDEX_MARKER)) {
        items.push(`- \`${indexPath}\` — default Akan landing page; replace it with your own home page.`);
      }
    }
  }
  if (items.length === 0) return "";
  return `## Start Clean (Remove Scaffolded Samples)

This workspace was scaffolded with reference samples so the Akan conventions are visible in real code. They are
not part of your product. Before building real features, remove the samples below and run \`akan sync <app>\`:

${items.join("\n")}

Keep a sample only while you are still learning its pattern; delete it once your own modules cover the same ground.

`;
};

// The always-present recipe index — **framework recipes only**. App/lib recipes are indexed in each
// app/lib's own generated `AGENTS.md` (scope-loaded, so the always-loaded context does not grow with the
// number of apps, and an agent never sees recipes it cannot import). Compact by design — names + import +
// variant signature + one-line doc (variants are typed, so tsc catches variant mistakes).
const renderRecipeIndex = async (workspace: Workspace) => {
  const sources = await collectRecipeSources(`${workspace.workspaceRoot}/pkgs/akanjs/ui`, "akanjs/ui", "recipe");
  const recipes = scanRecipes(sources);
  const scopeIndexPointer = `App and lib recipes are **not** listed here. Each app/lib carries its own generated index —
\`apps/<app>/AGENTS.md\` / \`libs/<lib>/AGENTS.md\` (\`## Recipes In Scope\`) — regenerated by \`akan sync\` and
verified by \`akan lint\`. When working inside an app or lib, consult that file before consuming or authoring a look.`;
  if (recipes.length === 0) return `## Recipes\n\n${scopeIndexPointer}\n\n`;
  return `## Recipes

Framework UI recipes (Tailwind-variant look factories), importable from every app and lib. Consume by exact name —
\`import { <name> } from "akanjs/ui"\`, then \`<name>(variants?, className?)\`. The second arg merges internally and
takes **an array too**, so never wrap it in \`cn()\`: \`<name>({}, ["h-full", isWide && "w-full", className])\`.
Do not guess recipe names, import paths, or variant values; the list below carries
the full contract (\`*\` marks the default, \`key?\` is a boolean flag), so there is no need to open the recipe file to
consume one. tsc still reports variant mistakes. **Before inlining a repeated surface (card, box,
tile, …): reuse a recipe, or add one as \`apps/<app>/ui/Recipe/<name>.ts\` (one recipe per file, re-exported from
that folder's \`index.ts\`) — never re-implement the same look inline in several places, and never author a
near-duplicate.** Full authoring/consumption policy: the \`recipeRule\` guideline.

${renderRecipeEntries(recipes)}

${scopeIndexPointer}

`;
};

// The convention set and the onboarding guide ship inside the package, so a framework release reaches an
// existing workspace through `akan agent install` instead of leaving a copy that was written once at create
// time. Onboarding is skipped in the framework monorepo itself: it teaches how to build *on* Akan, and pairing
// it with the conventions would more than double an always-loaded file for readers who are changing Akan.
const renderGuides = async (context: AkanWorkspaceContext) => {
  const conventions = (await Prompter.getInstruction("conventions")).trim();
  if (context.pkgs.some((pkg) => pkg.name === "akanjs")) return conventions;
  const onboarding = (await Prompter.getInstruction("workspaceOnboarding")).trim();
  const appName = context.apps[0]?.name ?? "app";
  return `${conventions}\n\n${onboarding.replaceAll("<%= appName %>", appName)}`;
};

// The generated, workspace-derived section. It is the only part of AGENTS.md that
// `akan agent install` rewrites; everything outside the markers is preserved.
const renderManagedBlock = async (workspace: Workspace) => {
  const context = await AkanContextAnalyzer.analyze(workspace);
  const frameworkGuide = await Prompter.getInstruction("framework");
  const appNames = context.apps.map((app) => app.name);
  const sampleCleanup = await renderSampleCleanup(workspace, appNames);
  const recipeIndex = await renderRecipeIndex(workspace);
  const guides = await renderGuides(context);
  const version = await readDevkitVersion();
  const block = `## Workspace

- Repo: ${context.repoName}
- Apps: ${context.apps.map((app) => app.name).join(", ") || "none"}
- Libraries: ${context.libs.map((lib) => lib.name).join(", ") || "none"}
- Packages: ${context.pkgs.map((pkg) => pkg.name).join(", ") || "none"}

${guides}

${sampleCleanup}## Akan Module Abstracts

- Before changing a domain, service, or scalar module, read its \`*.abstract.md\` file first.
- Update the abstract when business invariants, workflows, or public behavior change.
- Do not update the abstract for formatting-only, import-only, or style-only changes.
- Service modules live in \`lib/_<service>\`, but their abstract file is \`<service>.abstract.md\`.
- Keep an abstract short. Run \`akan compact <app-or-lib>\` to rewrite bloated abstracts down to the invariants the code cannot show; \`akan quality scan\` warns past 300 lines.

## Generated Files

Do not hand-edit generated Akan files such as ${context.generatedFiles.map((file) => `\`${file}\``).join(", ")}.
If generated output is stale or broken, update the owning source file and run \`akan repair generated\` or \`akan sync <app-or-lib>\`.

${recipeIndex}## MCP Workflow Policy

- Prefer Akan MCP workflows before direct source edits.
- Direct source edits are denied when an allowlisted Akan workflow or repair tool can perform the change.
- Use \`akan mcp --mode plan\` to inspect \`list_workflows\`, \`explain_workflow\`, and \`plan_workflow\`.
- If \`plan_workflow\` returns \`planPath\` or \`next.tool=apply_workflow\`, call \`apply_workflow({ planPath })\` before editing source files directly.
- Use \`akan mcp --mode apply\` only for allowlisted \`apply_workflow\`, \`run_validation\`, and repair tools.
- After \`apply_workflow\`, run \`run_validation\` with \`validationTarget\` when present; otherwise use \`applyReportPath\`.
- If no workflow exists, or apply reports unsupported/no-op/failed diagnostics that require manual action, keep edits scoped to owning source files and never patch generated files directly.
- For compound requests, split the request into workflows and apply each \`planPath\` in order, such as \`create-module\` followed by \`add-field\`.
- **CLI-only fallback (MCP not connected):** \`akan mcp\` starts a stdio MCP server, so the \`list_workflows\`/\`plan_workflow\`/\`apply_workflow\` tools exist only when your agent is wired to it as an MCP client. When they are unavailable, the CLI is a first-class equivalent: \`akan workflow list\` / \`explain <name>\` / \`plan <name> ... --format json --out <planPath>\` / \`apply <planPath> --format json\`, \`akan doctor --strict --format json\` for validation, and \`akan repair generated|imports|module-shape --app <app> --format json\` for repairs. Scaffolding primitives (\`create-module\`/\`create-scalar\`/\`create-service\` take the target app/lib as a POSITIONAL arg; \`add-field\`/\`add-enum-field\` use \`--app\`/\`--module\` flags) call the same code the workflows do.

## Validation

${context.validationCommands.map((command) => `- \`${command}\``).join("\n")}

## Framework Guide

${frameworkGuide.trim()}

## Before You Finish

1. \`bun run akan lint <appName>\` — Tailwind class order, \`Err\`, \`console\`, \`#private\` scope, unused imports.
2. \`bun run akan typecheck <appName>\` — server/client boundary violations.
3. \`bun run akan sync <appName>\` if you added, renamed, or deleted any file.
4. Did you write or change a \`.tsx\` file? \`bun run akan quality ssr\` — did the server share hold, and did you add
   a \`"use client"\` you cannot justify?
5. Re-read the file you wrote against its section above.
6. Did you add a comment? Delete it unless it documents an external constraint or a security decision.
7. Did behavior or an invariant change? Update the module's \`*.abstract.md\`.`;
  return version ? stampBlockVersion(block, version) : block;
};

const renderAgentsMd = async (workspace: Workspace, existing: string | null) => {
  const block = await renderManagedBlock(workspace);
  if (existing?.trim()) return upsertAgentBlock(existing, block);
  const context = await AkanContextAnalyzer.analyze(workspace);
  return `# ${context.repoName} Agent Guide

This file is the single source of truth for coding agents in this workspace. Claude Code reads it through
\`CLAUDE.md\` (\`@AGENTS.md\`) and Cursor through \`.cursor/rules/akan.mdc\`. The section between the
\`akan:agent\` markers is regenerated by \`akan agent install\`; edit anything outside the markers freely.

${AGENT_BLOCK_START}
${block}
${AGENT_BLOCK_END}
`;
};

// Claude Code natively imports other files with \`@path\`, so CLAUDE.md stays a pointer to AGENTS.md instead of
// duplicating its content. The comment rule is the one exception — see CLAUDE_COMMENT_RULE for why it is restated.
const renderClaudeMd = async (workspace: Workspace) => {
  const context = await AkanContextAnalyzer.analyze(workspace);
  return `# ${context.repoName} — Claude Code Guide

@AGENTS.md

${CLAUDE_COMMENT_RULE}
`;
};

// Cursor rules reference AGENTS.md rather than carrying their own copy.
const renderCursorRule = () => `---
description: Akan workspace agent guide
alwaysApply: true
---

Follow the workspace agent guide, which is the single source of truth for Akan conventions,
generated-file rules, and the MCP workflow policy.

@AGENTS.md
`;

const renderTarget = async (workspace: Workspace, target: AgentTarget, existing: string | null) => {
  if (target === "agents-md") return await renderAgentsMd(workspace, existing);
  if (target === "claude") return await renderClaudeMd(workspace);
  return renderCursorRule();
};

export class AgentRunner extends runner("agent") {
  async install(workspace: Workspace, targets: AgentTarget[], { force = false }: { force?: boolean } = {}) {
    const written: string[] = [];
    for (const target of targets) {
      const filePath = targetPaths[target];
      const exists = await workspace.exists(filePath);
      // AGENTS.md updates only the managed block, so refreshing an existing file is safe without --force.
      // CLAUDE.md and the Cursor rule are canonical pointers, so overwriting them needs --force.
      if (exists && !force && target !== "agents-md") {
        throw new Error(`${filePath} already exists. Re-run with --force to overwrite it.`);
      }
      const existing = exists ? await workspace.readFile(filePath) : null;
      const content = await renderTarget(workspace, target, existing);
      await workspace.writeFile(filePath, content, { overwrite: true });
      written.push(filePath);
    }
    if (targets.includes("agents-md")) written.push(...(await this.#installScopeIndexes(workspace)));
    return written;
  }

  // First-time layout of the scoped per-app/lib guides; afterwards `akan sync` (SysExecutor.scan) keeps them fresh.
  // Best-effort per scope: one whose config/env cannot load (fresh checkout, missing .env) must not block the
  // workspace-level install — `akan sync <name>` lays its file down once the scope is buildable.
  async #installScopeIndexes(workspace: Workspace) {
    const [appNames, libNames] = await workspace.getExecs();
    const written: string[] = [];
    const syncScope = async (exec: AppExecutor | LibExecutor) => {
      try {
        await exec.syncAgentsIndex();
        written.push(`${exec.type}s/${exec.name}/AGENTS.md`);
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        Logger.rawLog(`Skipped ${exec.type}s/${exec.name}/AGENTS.md (${message})`, undefined, "warn");
      }
    };
    for (const name of libNames) await syncScope(LibExecutor.from(workspace, name));
    for (const name of appNames) await syncScope(AppExecutor.from(workspace, name));
    return written;
  }
}
