export const signalText = {
  signal: { en: "Signal", ko: "시그널" },
  endpoints: { en: "Endpoints", ko: "엔드포인트" },
  restApi: { en: "REST API", ko: "REST API" },
  webSocket: { en: "Web Socket", ko: "웹소켓" },
  mcpTools: { en: "MCP Tools", ko: "MCP 도구" },
  baseUrl: { en: "Base URL", ko: "기본 URL" },
  guards: { en: "Guards", ko: "가드" },
  allGuards: { en: "All guards", ko: "모든 가드" },
  auth: { en: "Auth", ko: "인증" },
  authorized: { en: "Authorized", ko: "인증됨" },
  anonymous: { en: "Anonymous", ko: "익명" },
  searchEndpoints: { en: "Search endpoints", ko: "엔드포인트 검색" },
  setJwtTitle: { en: "Set JWT for Authorization", ko: "인증용 JWT 설정" },
  setAuthorization: { en: "Set Authorization", ko: "인증 설정" },
  bearerToken: { en: "Bearer token", ko: "Bearer 토큰" },
  accountDecoded: { en: "Account decoded", ko: "디코딩된 계정" },
  reference: { en: "Reference", ko: "명세" },
  tryIt: { en: "Try it", ko: "실행해 보기" },
  formData: { en: "Form data", ko: "폼 데이터" },
  pathParameters: { en: "Path parameters", ko: "경로 파라미터" },
  query: { en: "Query", ko: "쿼리" },
  body: { en: "Body", ko: "본문" },
  variables: { en: "Variables", ko: "변수" },
  returns: { en: "Returns", ko: "반환" },
  publishes: { en: "Publishes", ko: "발행" },
  example: { en: "Example", ko: "예시" },
  response: { en: "Response", ko: "응답" },
  responsePlaceholder: { en: "Send the request to see the response.", ko: "요청을 보내면 응답이 여기에 표시됩니다." },
  stream: { en: "Stream", ko: "스트림" },
  nothingReceived: { en: "Nothing received yet.", ko: "아직 받은 메시지가 없습니다." },
  sendRequest: { en: "Send Request", ko: "요청 보내기" },
  listen: { en: "Listen", ko: "수신" },
  send: { en: "Send", ko: "보내기" },
  stop: { en: "Stop", ko: "중지" },
  subscribe: { en: "Subscribe", ko: "구독" },
  unsubscribe: { en: "Unsubscribe", ko: "구독 해제" },
  noGuardMatch: { en: "No endpoint is gated by the selected guards.", ko: "선택한 가드가 걸린 엔드포인트가 없습니다." },
  noWsGuardMatch: {
    en: "No websocket endpoint is gated by the selected guards.",
    ko: "선택한 가드가 걸린 웹소켓 엔드포인트가 없습니다.",
  },
  noWsEndpoint: {
    en: "This signal declares no websocket endpoint.",
    ko: "이 시그널에는 웹소켓 엔드포인트가 없습니다.",
  },
  noSignal: { en: "No signal is registered.", ko: "등록된 시그널이 없습니다." },
  unknownOrigin: { en: "Unknown library", ko: "출처 미상" },
} as const;

export const guardCountText = (count: number) => ({ en: `${count} guards`, ko: `가드 ${count}개` });
export const noSignalText = (refName: string) => ({
  en: `No signal is registered as “${refName}”.`,
  ko: `“${refName}”(으)로 등록된 시그널이 없습니다.`,
});
export const noSearchMatchText = (search: string) => ({
  en: `No endpoint matches “${search}”.`,
  ko: `“${search}”와 일치하는 엔드포인트가 없습니다.`,
});
