//! Generated by scripts/contract.ts from packages/core/contract.json. Do not edit.
#![allow(dead_code)]

pub const ERROR_CODES: &[&str] = &["UNSUPPORTED", "PERMISSION_DENIED", "CANCELLED", "TIMEOUT", "INVALID_ARGS", "NOT_FOUND", "NOT_ALLOWED", "INTERNAL"];

/// File name extension → MIME type (assets and FileRefs).
pub const MIME: &[(&str, &str)] = &[
  ("html", "text/html"),
  ("htm", "text/html"),
  ("js", "text/javascript"),
  ("mjs", "text/javascript"),
  ("css", "text/css"),
  ("json", "application/json"),
  ("map", "application/json"),
  ("webmanifest", "application/manifest+json"),
  ("txt", "text/plain"),
  ("text", "text/plain"),
  ("log", "text/plain"),
  ("md", "text/markdown"),
  ("csv", "text/csv"),
  ("tsv", "text/tab-separated-values"),
  ("xml", "application/xml"),
  ("yaml", "application/yaml"),
  ("yml", "application/yaml"),
  ("ics", "text/calendar"),
  ("vcf", "text/vcard"),
  ("pdf", "application/pdf"),
  ("rtf", "application/rtf"),
  ("zip", "application/zip"),
  ("gz", "application/gzip"),
  ("tar", "application/x-tar"),
  ("wasm", "application/wasm"),
  ("epub", "application/epub+zip"),
  ("doc", "application/msword"),
  ("docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
  ("xls", "application/vnd.ms-excel"),
  ("xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
  ("ppt", "application/vnd.ms-powerpoint"),
  ("pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation"),
  ("png", "image/png"),
  ("jpg", "image/jpeg"),
  ("jpeg", "image/jpeg"),
  ("gif", "image/gif"),
  ("webp", "image/webp"),
  ("avif", "image/avif"),
  ("heic", "image/heic"),
  ("heif", "image/heif"),
  ("bmp", "image/bmp"),
  ("svg", "image/svg+xml"),
  ("ico", "image/x-icon"),
  ("tif", "image/tiff"),
  ("tiff", "image/tiff"),
  ("mp3", "audio/mpeg"),
  ("m4a", "audio/mp4"),
  ("aac", "audio/aac"),
  ("wav", "audio/wav"),
  ("ogg", "audio/ogg"),
  ("flac", "audio/flac"),
  ("mp4", "video/mp4"),
  ("m4v", "video/mp4"),
  ("mov", "video/quicktime"),
  ("webm", "video/webm"),
  ("ttf", "font/ttf"),
  ("otf", "font/otf"),
  ("woff", "font/woff"),
  ("woff2", "font/woff2"),
  ("glb", "model/gltf-binary"),
  ("gltf", "model/gltf+json"),
];

/// Besides text/*, the asset types served with charset=utf-8.
pub const MIME_UTF8: &[&str] = &["application/json", "application/manifest+json", "application/xml", "application/yaml", "image/svg+xml", "model/gltf+json"];

/// An id grammar: allowed characters, length, and an optional extension after the first dot.
pub struct IdSpec {
  pub chars: &'static str,
  pub first: &'static str,
  pub not_first: &'static str,
  pub min: usize,
  pub max: usize,
  pub ext_chars: &'static str,
  pub ext_max: usize,
}

pub const ID_FILE_REF: IdSpec = IdSpec { chars: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-", first: "", not_first: "", min: 1, max: 128, ext_chars: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789", ext_max: 8 };
pub const ID_BUNDLE: IdSpec = IdSpec { chars: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_.-", first: "", not_first: ".", min: 1, max: 80, ext_chars: "", ext_max: 0 };
pub const ID_DOCUMENT: IdSpec = IdSpec { chars: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-", first: "", not_first: "", min: 8, max: 64, ext_chars: "", ext_max: 0 };
pub const ID_NAME: IdSpec = IdSpec { chars: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_.-", first: "$ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz", not_first: "", min: 1, max: 64, ext_chars: "", ext_max: 0 };

pub const EXTERNAL_SCHEMES: &[&str] = &["http", "https", "mailto", "tel"];
pub const FRAME_SCHEMES: &[&str] = &["http", "https", "data", "blob", "about"];
/// Schemes an app can never add to the external list.
pub const NEVER_EXTERNAL_SCHEMES: &[&str] = &["javascript", "vbscript", "file", "data", "blob", "about", "content", "intent", "app"];

pub const ROUTE_ROOT: &str = "__akan_native";
pub const ROUTE_INIT: &str = "init.js";
pub const ROUTE_IPC: &str = "ipc";
pub const ROUTE_HELLO: &str = "hello";
pub const ROUTE_FILE: &str = "file";

pub const INIT_PREFIX: &str = "window.__AKAN_NATIVE__=(function(o,b,e){for(var k in b)o[k]=b[k];o.env=e;return o})(window.__AKAN_NATIVE__||{},";
pub const INIT_SUFFIX: &str = ");\n";
pub const MAX_RANGE_BYTES: usize = 1024000;
pub const EXTERNAL_OPENS_PER_SECOND: u32 = 1;
pub const MAX_RETAINED_EVENTS: usize = 16;
