// Generated by scripts/contract.ts from packages/core/contract.json. Do not edit.

/// An id grammar: allowed characters, length, and an optional extension after the first dot.
struct AkanNativeIdSpec: Sendable {
    let chars: String
    let first: String
    let notFirst: String
    let min: Int
    let max: Int
    let extChars: String
    let extMax: Int
}

enum AkanNativeContract {
    static let errorCodes: [String] = ["UNSUPPORTED", "PERMISSION_DENIED", "CANCELLED", "TIMEOUT", "INVALID_ARGS", "NOT_FOUND", "NOT_ALLOWED", "INTERNAL"]

    /// File name extension → MIME type (assets and FileRefs).
    static let mime: [String: String] = [
        "html": "text/html",
        "htm": "text/html",
        "js": "text/javascript",
        "mjs": "text/javascript",
        "css": "text/css",
        "json": "application/json",
        "map": "application/json",
        "webmanifest": "application/manifest+json",
        "txt": "text/plain",
        "text": "text/plain",
        "log": "text/plain",
        "md": "text/markdown",
        "csv": "text/csv",
        "tsv": "text/tab-separated-values",
        "xml": "application/xml",
        "yaml": "application/yaml",
        "yml": "application/yaml",
        "ics": "text/calendar",
        "vcf": "text/vcard",
        "pdf": "application/pdf",
        "rtf": "application/rtf",
        "zip": "application/zip",
        "gz": "application/gzip",
        "tar": "application/x-tar",
        "wasm": "application/wasm",
        "epub": "application/epub+zip",
        "doc": "application/msword",
        "docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "xls": "application/vnd.ms-excel",
        "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "ppt": "application/vnd.ms-powerpoint",
        "pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "png": "image/png",
        "jpg": "image/jpeg",
        "jpeg": "image/jpeg",
        "gif": "image/gif",
        "webp": "image/webp",
        "avif": "image/avif",
        "heic": "image/heic",
        "heif": "image/heif",
        "bmp": "image/bmp",
        "svg": "image/svg+xml",
        "ico": "image/x-icon",
        "tif": "image/tiff",
        "tiff": "image/tiff",
        "mp3": "audio/mpeg",
        "m4a": "audio/mp4",
        "aac": "audio/aac",
        "wav": "audio/wav",
        "ogg": "audio/ogg",
        "flac": "audio/flac",
        "mp4": "video/mp4",
        "m4v": "video/mp4",
        "mov": "video/quicktime",
        "webm": "video/webm",
        "ttf": "font/ttf",
        "otf": "font/otf",
        "woff": "font/woff",
        "woff2": "font/woff2",
        "glb": "model/gltf-binary",
        "gltf": "model/gltf+json",
    ]

    /// Besides text/*, the asset types served with charset=utf-8.
    static let mimeUtf8: Set<String> = ["application/json", "application/manifest+json", "application/xml", "application/yaml", "image/svg+xml", "model/gltf+json"]

    static let idFileRef = AkanNativeIdSpec(chars: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-", first: "", notFirst: "", min: 1, max: 128, extChars: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789", extMax: 8)
    static let idBundle = AkanNativeIdSpec(chars: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_.-", first: "", notFirst: ".", min: 1, max: 80, extChars: "", extMax: 0)
    static let idDocument = AkanNativeIdSpec(chars: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-", first: "", notFirst: "", min: 8, max: 64, extChars: "", extMax: 0)
    static let idName = AkanNativeIdSpec(chars: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_.-", first: "$ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz", notFirst: "", min: 1, max: 64, extChars: "", extMax: 0)

    static let externalSchemes: [String] = ["http", "https", "mailto", "tel"]
    static let frameSchemes: [String] = ["http", "https", "data", "blob", "about"]
    /// Schemes an app can never add to the external list.
    static let neverExternalSchemes: [String] = ["javascript", "vbscript", "file", "data", "blob", "about", "content", "intent", "app"]

    static let routeRoot = "__akan_native"
    static let routeInit = "init.js"
    static let routeIpc = "ipc"
    static let routeHello = "hello"
    static let routeFile = "file"

    static let initPrefix = "window.__AKAN_NATIVE__=(function(o,b,e){for(var k in b)o[k]=b[k];o.env=e;return o})(window.__AKAN_NATIVE__||{},"
    static let initSuffix = ");\n"
    static let maxRangeBytes = 1024000
    static let externalOpensPerSecond = 1
    static let maxRetainedEvents = 16
}
