const FIREBASE_WEB_SDK_VERSION = "12.13.0";

export interface FirebaseClientEnvConfig {
  apiKey: string;
  authDomain?: string;
  projectId: string;
  storageBucket?: string;
  messagingSenderId: string;
  appId: string;
  vapidKey?: string;
}

//* env.client 의 firebase 설정을 검증하고, 서비스워커에 필요한 필드만 화이트리스트한다.
//* vapidKey/서버 시크릿 등 나머지 필드는 의도적으로 제외한다(SW 본문에 유출 방지).
export function normalizeFirebaseClientConfig(config: unknown): FirebaseClientEnvConfig | null {
  if (!config || typeof config !== "object") return null;
  const value = config as Partial<Record<keyof FirebaseClientEnvConfig, unknown>>;
  if (
    typeof value.apiKey !== "string" ||
    typeof value.projectId !== "string" ||
    typeof value.messagingSenderId !== "string" ||
    typeof value.appId !== "string"
  ) {
    return null;
  }
  return {
    apiKey: value.apiKey,
    ...(typeof value.authDomain === "string" ? { authDomain: value.authDomain } : {}),
    projectId: value.projectId,
    ...(typeof value.storageBucket === "string" ? { storageBucket: value.storageBucket } : {}),
    messagingSenderId: value.messagingSenderId,
    appId: value.appId,
  };
}

//* firebase-messaging-sw.js 생성 코드
export function createFirebaseMessagingServiceWorker(config: FirebaseClientEnvConfig | null): string {
  const configJson = JSON.stringify(config);
  return `/* Generated by Akan.js. Do not edit. */
const firebaseConfig = ${configJson};

if (firebaseConfig) {
  importScripts("https://www.gstatic.com/firebasejs/${FIREBASE_WEB_SDK_VERSION}/firebase-app-compat.js");
  importScripts("https://www.gstatic.com/firebasejs/${FIREBASE_WEB_SDK_VERSION}/firebase-messaging-compat.js");

  firebase.initializeApp(firebaseConfig);
  const messaging = firebase.messaging();

  const notificationUrl = (payload) =>
    payload?.data?.url || payload?.fcmOptions?.link || payload?.notification?.click_action;

  messaging.onBackgroundMessage((payload) => {
    const title = payload?.notification?.title || "";
    const options = {
      body: payload?.notification?.body,
      icon: payload?.notification?.icon,
      image: payload?.notification?.image,
      data: {
        url: notificationUrl(payload),
        FCM_MSG: payload,
      },
    };
    self.registration.showNotification(title, options);
  });
}

self.addEventListener("notificationclick", (event) => {
  const url = event.notification?.data?.url || event.notification?.data?.FCM_MSG?.data?.url;
  event.notification?.close();
  if (!url) return;
  event.waitUntil(clients.openWindow(url));
});
`;
}
