// google-services.json → Android string resources (the push plugin's FCM module, akanjs readiness O6-2),
// what the google-services Gradle plugin generates: Firebase reads these by name from the app's package
// (FirebaseOptions.fromResource). The client is the one for the app's package name; a debug build's
// suffixed id falls back to the base id's client.

import { CliError } from "./log.ts";

interface GoogleServices {
  project_info?: { project_number?: string; project_id?: string; storage_bucket?: string; firebase_url?: string };
  client?: {
    client_info?: { mobilesdk_app_id?: string; android_client_info?: { package_name?: string } };
    api_key?: { current_key?: string }[];
    oauth_client?: { client_id?: string; client_type?: number }[];
  }[];
}

const escape = (s: string) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/'/g, "\\'").replace(/"/g, '\\"');

/** res/values/google_services.xml for `packageName` (and `fallbackPackage` when it has no client). */
export function googleServicesXml(json: string, packageName: string, fallbackPackage = packageName): string {
  let parsed: GoogleServices;
  try {
    parsed = JSON.parse(json) as GoogleServices;
  } catch (error) {
    throw new CliError(`android.googleServices: not JSON (${(error as Error).message})`);
  }
  const clients = parsed.client ?? [];
  const client =
    clients.find((c) => c.client_info?.android_client_info?.package_name === packageName) ??
    clients.find((c) => c.client_info?.android_client_info?.package_name === fallbackPackage);
  if (!client) {
    const names = clients.map((c) => c.client_info?.android_client_info?.package_name).filter(Boolean);
    throw new CliError(
      `android.googleServices has no Android app ${packageName} (it has ${names.join(", ") || "none"}): add it in the Firebase console and download the file again`,
    );
  }
  const values: [string, string | undefined][] = [
    ["google_app_id", client.client_info?.mobilesdk_app_id],
    ["gcm_defaultSenderId", parsed.project_info?.project_number],
    ["google_api_key", client.api_key?.[0]?.current_key],
    ["google_crash_reporting_api_key", client.api_key?.[0]?.current_key],
    ["project_id", parsed.project_info?.project_id],
    ["google_storage_bucket", parsed.project_info?.storage_bucket],
    ["firebase_database_url", parsed.project_info?.firebase_url],
    ["default_web_client_id", client.oauth_client?.find((o) => o.client_type === 3)?.client_id],
  ];
  if (!values[0]![1] || !values[1]![1] || !values[2]![1])
    throw new CliError(
      "android.googleServices lacks mobilesdk_app_id, project_number or api_key: download it again from the Firebase console",
    );
  const lines = values
    .filter(([, v]) => v)
    .map(([k, v]) => `    <string name="${k}" translatable="false">${escape(v!)}</string>`);
  return `<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by akan-native build from android.googleServices. -->\n<resources>\n${lines.join("\n")}\n</resources>\n`;
}
