// The shared vectors (packages/core/vectors) as source code for the Swift and Kotlin hosts'
// runners (AkanNativeVectors.swift, AkanNativeVectors.kt). scripts/native-vectors.ts compiles them on the Mac
// (swiftc, the pinned kotlinc on the JVM); debug builds compile them into the app, where the
// self-test runs them on the device through $host.vectors. Release builds get empty data.
//
// Swift reads the JSON text with JSONSerialization, which is what its bridge parses requests with.
// Kotlin gets literals (no JSON reader on the JVM: android.jar's org.json is only stubs there).

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { PACKAGE_ROOT } from "./root.ts";

export const VECTOR_FILES = [
  "scope",
  "routes",
  "ranges",
  "ids",
  "bridge",
  "navigation",
  "acl",
  "retained",
  "ed25519",
] as const;

/**
 * How many checks each file holds: the runners fail when a file is missing or ran another number,
 * so an empty or truncated file cannot pass as zero checks.
 */
export function vectorCounts(): Record<string, number> {
  const v = vectors() as Record<string, any>;
  const n = (a: unknown) => (Array.isArray(a) ? a.length : 0);
  return {
    scope: n(v.scope.glob) + n(v.scope.url) + n(v.scope.permits),
    routes: n(v.routes.cases) + n(v.routes.hostPaths),
    ranges: n(v.ranges.cases),
    ids: n(v.ids.cases) + n(v.ids.mime?.cases),
    bridge: n(v.bridge.requests) + n(v.bridge.declarations) + n(v.bridge.documents),
    navigation: n(v.navigation.cases) + n(v.navigation.fileRefSandbox),
    acl: (v.acl.cases as { checks: unknown[] }[]).reduce((sum, c) => sum + 1 + c.checks.length, 0),
    retained: n(v.retained.cases),
    ed25519: n(v.ed25519.cases),
  };
}

function vectors(): Record<string, unknown> {
  return Object.fromEntries(
    VECTOR_FILES.map((name) => [
      name,
      JSON.parse(readFileSync(join(PACKAGE_ROOT, "packages/core/vectors", `${name}.json`), "utf8")),
    ]),
  );
}

/** AkanNativeVectorData.swift: the vector files as JSON text (empty for release builds). */
export function swiftVectorData(withVectors: boolean): string {
  const entries = withVectors
    ? Object.entries(vectors()).map(([name, value]) => `        "${name}": ##"${JSON.stringify(value)}"##,`)
    : [];
  const counts = withVectors
    ? Object.entries(vectorCounts()).map(([name, count]) => `        "${name}": ${count},`)
    : [];
  return [
    "// Generated by akan-native (packages/cli/src/lib/vectors.ts) from packages/core/vectors. Do not edit.",
    "",
    "enum AkanNativeVectorData {",
    `    static let files: [String: String] = [${entries.length ? "" : ":"}`,
    ...entries,
    "    ]",
    "    /// The checks each file holds; the runner fails when another number ran.",
    `    static let counts: [String: Int] = [${counts.length ? "" : ":"}`,
    ...counts,
    "    ]",
    "}",
    "",
  ].join("\n");
}

function kotlinString(text: string): string {
  let out = "";
  for (const ch of text) {
    const code = ch.codePointAt(0)!;
    if (ch === "\\" || ch === '"' || ch === "$") out += `\\${ch}`;
    else if (code < 0x20 || code === 0x2028 || code === 0x2029) out += `\\u${code.toString(16).padStart(4, "0")}`;
    else out += ch;
  }
  return `"${out}"`;
}

function kotlinValue(value: unknown): string {
  if (value === null) return "null";
  if (typeof value === "boolean") return String(value);
  if (typeof value === "number") return Number.isInteger(value) ? `${value}L` : String(value);
  if (typeof value === "string") return kotlinString(value);
  if (Array.isArray(value)) return `listOf<Any?>(${value.map(kotlinValue).join(", ")})`;
  return `mapOf<String, Any?>(${Object.entries(value as Record<string, unknown>)
    .map(([k, v]) => `${kotlinString(k)} to ${kotlinValue(v)}`)
    .join(", ")})`;
}

/**
 * AkanNativeVectorData.kt: each vector file as a function returning Kotlin values (Map, List, String,
 * Long, Double, Boolean, null); one function per file keeps each under the JVM's method size limit.
 */
export function kotlinVectorData(withVectors: boolean): string {
  const all = withVectors ? Object.entries(vectors()) : [];
  return [
    "// Generated by akan-native (packages/cli/src/lib/vectors.ts) from packages/core/vectors. Do not edit.",
    "package com.akanjs.runtime",
    "",
    "object AkanNativeVectorData {",
    "    /** The checks each file holds; the runner fails when another number ran. */",
    `    val counts: Map<String, Int> = mapOf(${
      withVectors
        ? Object.entries(vectorCounts())
            .map(([name, count]) => `${kotlinString(name)} to ${count}`)
            .join(", ")
        : ""
    })`,
    `    fun file(name: String): Map<String, Any?>? = when (name) {`,
    ...all.map(([name]) => `        ${kotlinString(name)} -> ${name}()`),
    "        else -> null",
    "    }",
    ...all.flatMap(([name, value]) => ["", `    private fun ${name}(): Map<String, Any?> = ${kotlinValue(value)}`]),
    "}",
    "",
  ].join("\n");
}
