import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { type BackendEnv, ID } from "akanjs/base";
import { Logger } from "akanjs/common";
import { ConstantRegistry, via } from "akanjs/constant";
import { endpoint } from "../../signal/endpoint";
import type { Guard, GuardScope } from "../../signal/guard";
import { None, Public } from "../../signal/guards";
import { internal } from "../../signal/internal";
import { McpProgress, Msg } from "../../signal/mcp";
import { serverSignal } from "../../signal/serverSignal";
import { SignalRegistry } from "../../signal/signalRegistry";
import { slice } from "../../signal/slice";
import { AkanLib } from "../akanLib";
import { AkanOption } from "../akanOption";
import { DiLifecycle } from "../di/diLifecycle";
import {
  ServerResolverTestLight,
  serverResolverTestConstant,
  serverResolverTestDatabase,
  serverResolverTestServiceModel,
} from "../resolver/resolver.contract.fixture";
import type { SignalRoutes } from "../types";
import { McpRouter, type McpRouterProps } from "./McpRouter";

/**
 * Exercises the whole execution path an MCP tool call takes — document → dispatcher → `McpExecutionContext` →
 * `SignalContext` → guards and middleware → service → serialization — against a booted DI container. The unit
 * tests cover the wire format; this is the one that would catch the context being wired to the wrong transport.
 *
 * The shared resolver fixture supplies the model and service, but the signals are declared here: opting that
 * fixture into MCP would change what every other test sees serialized.
 */
/** Says yes like `Public` does, but is a real guard — which is the whole difference an exposed mutation turns on. */
class SignedIn implements Guard {
  static name = "SignedIn";
  static scope: GuardScope = "account";
  canPass() {
    return true;
  }
}

/**
 * A model whose Light carries a `visual` field. Declared here rather than in the shared resolver fixture for the
 * same reason the signals are: a field added there changes what every other test sees serialized.
 */
const McpVisualInput = via((f) => ({
  title: f(String),
  preview: f.visual(String),
}));
const McpVisualObject = via(McpVisualInput, () => ({}));
const McpVisualLight = via(McpVisualObject, ["title", "preview"] as const, () => ({}));
const McpVisualFull = via(McpVisualObject, McpVisualLight, () => ({}));
const McpVisualInsight = via(McpVisualFull, () => ({}));
ConstantRegistry.buildModel(
  "mcpVisualItem",
  McpVisualInput,
  McpVisualObject,
  McpVisualFull,
  McpVisualLight,
  McpVisualInsight,
  {},
);

class McpItemSlice extends slice(
  serverResolverTestServiceModel,
  // `list` is the root slice's own opt-in — it is generated by `slice()`, so there is nowhere else to write it.
  { guards: { root: Public, get: Public, cru: Public } },
  (init) => ({
    inCategory: init({ guards: [Public] })
      .search("category", String)
      .exec(function (category) {
        return this.serverResolverTestItemService.queryInCategory(category ?? "all");
      }),
  }),
) {}

class McpItemEndpoint extends endpoint(serverResolverTestServiceModel, (builder) => ({
  echoTitle: builder
    .query(String, { guards: [Public] })
    .param("id", ID)
    .search("suffix", String)
    .exec((id, suffix) => `${id}:${suffix ?? "none"}`),
  // Declares no guards at all, which is what keeps it out of the catalogue now that exposure follows them.
  hiddenTitle: builder
    .query(String)
    .param("id", ID)
    .exec((id) => `hidden:${id}`),
  joinTags: builder
    .query(String, { guards: [Public] })
    .search("tags", [String])
    .exec((tags) => (tags ?? []).join("|")),
  maybeItem: builder
    .query(ServerResolverTestLight, { guards: [Public], nullable: true })
    .search("title", String)
    .exec((title) =>
      title
        ? {
            id: "507f1f77bcf86cd799439011",
            title,
            category: "all",
            createdAt: new Date(0),
            updatedAt: new Date(0),
            removedAt: null,
          }
        : null,
    ),
  visualItem: builder.query(McpVisualLight, { guards: [Public] }).exec(() => ({
    id: "507f1f77bcf86cd799439011",
    title: "shot",
    preview: "data:image/png;base64,AAAA",
    createdAt: new Date(0),
    updatedAt: new Date(0),
    removedAt: null,
  })),
  failingTitle: builder.query(String, { guards: [Public] }).exec(() => {
    throw new Error("boom: internal detail that must not travel");
  }),
  deniedTitle: builder.query(String, { guards: [None] }).exec(() => "denied"),
  slowTitle: builder.query(String, { guards: [Public] }).exec(async () => {
    McpProgress.report(1, { total: 2, message: "counting" });
    await new Promise((resolve) => setTimeout(resolve, 5));
    McpProgress.report(2, { total: 2 });
    return "counted";
  }),
  renameTitle: builder
    .mutation(String, { guards: [SignedIn] })
    .param("id", ID)
    .body("title", String)
    .exec((id, title) => `${id}:${title}`),
  publicRenameTitle: builder
    .mutation(String, { guards: [Public] })
    .param("id", ID)
    .exec((id) => `${id}:public`),
  reviewItem: builder
    .prompt({ guards: [Public] })
    .param("id", ID)
    .search("tone", String)
    .exec((id, tone) => [Msg.user(`Review ${id} in a ${tone ?? "neutral"} tone.`), Msg.link(`akan://item/${id}`)]),
  briefItem: builder.prompt({ guards: [Public] }).exec(() => "Answer in three sentences."),
  brokenItem: builder
    .prompt({ guards: [Public] })
    .exec(() => [{ role: "system", content: { type: "text", text: "x" } }] as never),
  deniedItem: builder.prompt({ guards: [None] }).exec(() => "denied"),
})) {}

class McpItemInternal extends internal(serverResolverTestServiceModel, () => ({})) {}
class McpItemServerSignal extends serverSignal(McpItemEndpoint, McpItemInternal) {}

const createEnv = (tmp: string) =>
  ({
    workspaceRoot: tmp,
    database: {
      sqlite: { filePath: join(tmp, "akan.db"), journalMode: "WAL", busyTimeoutMs: 1000, foreignKeys: true },
    },
    solid: {
      filePath: join(tmp, "solid.db"),
      journalMode: "WAL",
      busyTimeoutMs: 1000,
      cleanupIntervalMs: 60_000,
      queuePollIntervalMs: 60_000,
      queueLeaseMs: 30_000,
    },
  }) satisfies BackendEnv & { workspaceRoot: string };

let tmp = "";
let di: DiLifecycle;
let httpRoutes: NonNullable<SignalRoutes["routes"]>;
let post: (body: object) => Promise<{ res: Response; json: any }>;
let postPaged: (body: object, pageSize: number) => Promise<{ res: Response; json: any }>;
let postWith: (body: object, props: Partial<McpRouterProps>) => Promise<{ res: Response; json: any }>;
let postRaw: (body: object, headers: Record<string, string>) => Promise<Response>;
let mcpRouter: (props?: Partial<McpRouterProps>) => McpRouter;
let mcpRoutes: (props?: Partial<McpRouterProps>) => Record<string, Record<string, (req: Request) => Promise<Response>>>;

beforeAll(async () => {
  process.env.AKAN_PUBLIC_APP_NAME = "mcpIntegration";
  process.env.AKAN_PUBLIC_REPO_NAME = "akan";
  process.env.AKAN_PUBLIC_SERVE_DOMAIN = "example.com";
  process.env.AKAN_PUBLIC_ENV = "local";
  process.env.AKAN_PUBLIC_OPERATION_MODE = "local";
  process.env.SERVER_MODE = "all";
  tmp = await mkdtemp(join(tmpdir(), "akan-mcp-"));
  const env = createEnv(tmp);
  const lib = new AkanLib("mcpIntegrationTest", {
    databases: [
      {
        constant: serverResolverTestConstant,
        database: serverResolverTestDatabase,
        service: serverResolverTestServiceModel,
        signal: SignalRegistry.registerDatabase(
          "serverResolverTestItem",
          McpItemInternal,
          McpItemEndpoint,
          McpItemSlice,
          McpItemServerSignal,
        ),
      },
    ],
    services: [],
    scalars: [],
    option: new AkanOption(),
  });
  di = new DiLifecycle({ env }, lib);
  httpRoutes = (await di.initializeAll()).routes ?? {};
  mcpRouter = (props: Partial<McpRouterProps> = {}) =>
    new McpRouter({ registry: di.registry, live: di.live, middleware: new Map(di.modules.middleware), env, ...props });
  mcpRoutes = (props: Partial<McpRouterProps> = {}) =>
    mcpRouter(props).createRoutes() as Record<string, Record<string, (req: Request) => Promise<Response>>>;
  const send = async (body: object, headers: Record<string, string> = {}, props: Partial<McpRouterProps> = {}) => {
    const routes = mcpRoutes(props);
    return await routes["/mcp"].POST(
      new Request("http://127.0.0.1:8080/mcp", {
        method: "POST",
        body: JSON.stringify(body),
        headers: { "Content-Type": "application/json", ...headers },
      }),
    );
  };
  const withJson = async (res: Response) => ({ res, json: await res.json() });
  post = async (body: object) => await withJson(await send(body));
  postPaged = async (body: object, pageSize: number) => await withJson(await send(body, {}, { pageSize }));
  postWith = async (body: object, props: Partial<McpRouterProps>) => await withJson(await send(body, {}, props));
  postRaw = async (body: object, headers: Record<string, string>) => await send(body, headers);
});

afterAll(async () => {
  await di?.destroyAll();
  if (tmp) await rm(tmp, { recursive: true, force: true });
});

const call = async (name: string, args: Record<string, unknown> = {}) =>
  (await post({ jsonrpc: "2.0", id: 1, method: "tools/call", params: { name, arguments: args } })).json;

describe("MCP over a booted container", () => {
  test("lists every endpoint its guards admit", async () => {
    const { json } = await post({ jsonrpc: "2.0", id: 1, method: "tools/list" });
    expect(json.result.tools.map((tool: { name: string }) => tool.name)).toEqual([
      "echoTitle",
      "failingTitle",
      "joinTags",
      "lightServerResolverTestItem",
      "maybeItem",
      "renameTitle",
      "serverResolverTestItem",
      "serverResolverTestItemInsight",
      "serverResolverTestItemInsightInCategory",
      "serverResolverTestItemList",
      "serverResolverTestItemListInCategory",
      "slowTitle",
      "visualItem",
    ]);
  });

  test("refuses an exposed mutation whose only guard is Public", async () => {
    // `Public` answers true unconditionally, so a list containing only it is an unguarded write spelled out —
    // the exact thing the mutation check exists to keep off an agent's shelf.
    const { json } = await post({ jsonrpc: "2.0", id: 1, method: "tools/list" });
    expect(json.result.tools.map((tool: { name: string }) => tool.name)).not.toContain("publicRenameTitle");
    const called = await call("publicRenameTitle", { id: "507f1f77bcf86cd799439011" });
    expect(called.error.message).toBe("Unknown tool: publicRenameTitle.");
  });

  test("answers ping", async () => {
    // A utility of both eras, and a client that uses it as a liveness check reads a -32601 as a dead connection.
    const { json } = await post({ jsonrpc: "2.0", id: 1, method: "ping" });
    expect(json.result).toEqual({});
    expect(json.error).toBeUndefined();
  });

  test("hides what an account-scoped guard already refuses this caller", async () => {
    // `None` reads only the caller, so the answer is known before any argument exists. A resource guard is not
    // evaluated here at all, which is why `renameTitle` above stays listed and is stopped at call time instead.
    const { json } = await post({ jsonrpc: "2.0", id: 1, method: "tools/list" });
    expect(json.result.tools.map((tool: { name: string }) => tool.name)).not.toContain("deniedTitle");
    const prompts = await post({ jsonrpc: "2.0", id: 1, method: "prompts/list" });
    expect(prompts.json.result.prompts.map((prompt: { name: string }) => prompt.name)).not.toContain("deniedItem");
  });

  test("runs an opted-in guarded mutation", async () => {
    const json = await call("renameTitle", { id: "507f1f77bcf86cd799439011", title: "renamed" });
    expect(json.result.isError).toBe(false);
    expect(json.result.content[0].text).toBe("507f1f77bcf86cd799439011:renamed");
  });

  test("runs a tool through the signal pipeline and returns its value", async () => {
    const json = await call("echoTitle", { id: "507f1f77bcf86cd799439011", suffix: "tail" });
    expect(json.result.isError).toBe(false);
    // Not `"…"` with the quotes: JSON is how a structured result is mirrored as text, and a scalar has no
    // structured half to mirror — encoding one anyway spent the block on syntax a model has to know to strip.
    expect(json.result.content[0].text).toBe("507f1f77bcf86cd799439011:tail");
    // A scalar return promises no `outputSchema`, so it carries no structured result either.
    expect(json.result.structuredContent).toBeUndefined();
  });

  test("treats an omitted optional arg as absent rather than failing", async () => {
    const json = await call("echoTitle", { id: "507f1f77bcf86cd799439011" });
    expect(json.result.content[0].text).toBe("507f1f77bcf86cd799439011:none");
  });

  test("wraps a list result so structuredContent stays an object", async () => {
    const json = await call("serverResolverTestItemListInCategory", { category: "all", limit: 5 });
    expect(json.result.isError).toBe(false);
    expect(json.result.structuredContent).toEqual({ items: [] });
  });

  test("runs the two generated entries a slice opts in, not merely lists them", async () => {
    // The root list's raw `query` argument is typed `Any` and is left out of the published schema, so it has to
    // reach the endpoint as omitted — not as `{}`, and not as a required value the caller never saw declared.
    const list = await call("serverResolverTestItemList", { limit: 5 });
    expect(list.result.isError).toBe(false);
    expect(list.result.structuredContent).toEqual({ items: [] });
    const read = await post({
      jsonrpc: "2.0",
      id: 1,
      method: "resources/read",
      params: { uri: "akan://serverResolverTestItem/list?limit=5" },
    });
    expect(read.json.result.contents[0].text).toBe('{"items":[]}');
    // And the generated single-document tool answers a missing document the way its resource URI already does.
    const single = await call("serverResolverTestItem", { serverResolverTestItemId: "507f1f77bcf86cd799439011" });
    expect(single.result.isError).toBe(true);
    expect(single.result.content[0].text).toBe("No serverResolverTestItem found for the arguments given.");
  });

  test("ships an empty answer as text alone rather than as a null structuredContent", async () => {
    // `structuredContent: null` is a successful call the official client SDK throws on: the field is typed as an
    // object there, so a nullable model that found nothing has to travel the same way a scalar does.
    const empty = await call("maybeItem");
    expect(empty.result.isError).toBe(false);
    expect(empty.result.content[0].text).toBe("null");
    expect("structuredContent" in empty.result).toBe(false);
    const found = await call("maybeItem", { title: "here" });
    expect(found.result.structuredContent).toMatchObject({ title: "here" });
    const { json } = await post({ jsonrpc: "2.0", id: 1, method: "tools/list" });
    // And no schema is published for it, because a declared one obliges every result to match.
    expect(json.result.tools.find((tool: { name: string }) => tool.name === "maybeItem").outputSchema).toBeUndefined();
  });

  test("reports arguments that are not an object as the caller's own mistake", async () => {
    // Coerced to `{}`, this ran with every argument missing: a tool that takes none simply succeeded, and one
    // that takes some answered "Missing required argument", sending a model to look for a value it did send.
    const called = await post({
      jsonrpc: "2.0",
      id: 1,
      method: "tools/call",
      params: { name: "echoTitle", arguments: "oops" },
    });
    expect(called.json.error.code).toBe(-32602);
    expect(called.json.error.message).toBe("`arguments` must be an object of named values.");
    // An array is refused with the rest: MCP names its arguments, so positional ones would read as `0`, `1`, `2`.
    const positional = await post({
      jsonrpc: "2.0",
      id: 1,
      method: "prompts/get",
      params: { name: "reviewItem", arguments: ["507f1f77bcf86cd799439011"] },
    });
    expect(positional.json.error.code).toBe(-32602);
    expect(positional.json.error.message).toBe("`arguments` must be an object of named values.");
  });

  test("advertises only the capabilities it actually has entries for", async () => {
    // A fixed `{ tools, resources, prompts }` invites three listing round-trips whatever the server carries.
    const { json } = await post({
      jsonrpc: "2.0",
      id: 1,
      method: "initialize",
      params: { protocolVersion: "2025-11-25", capabilities: {} },
    });
    expect(json.result.capabilities).toEqual({ tools: {}, resources: {}, prompts: {} });
  });

  test("says at boot what it published and what it refused", async () => {
    // Every rejection here is fail-closed and was silent: `publicRenameTitle` names a guard, opts in, and simply
    // is not there. `akan quality scan` cannot cover it — it reads source, where a return type and a guard list
    // are names rather than resolved types — so the boot log is the only place an author can be told.
    const lines: string[] = [];
    const stop = Logger.addSink(({ message }) => lines.push(message));
    try {
      mcpRouter().report();
      mcpRouter({ readOnly: true }).report();
    } finally {
      stop();
    }
    const log = lines.join("\n");
    // The whole build, not one caller's view: `deniedTitle` and `deniedItem` are in the catalogue and are hidden
    // per credential at listing time, so these counts run ahead of what `tools/list` returned above.
    expect(log).toContain("MCP catalogue: tools=14 prompts=4 resourceTemplates=4");
    expect(lines.find((line) => line.includes('"publicRenameTitle"'))).toContain("`[Public]` is having none");
    // The read-only valve reports itself the same way, rather than leaving an author to wonder where a guarded,
    // deliberately exposed mutation went.
    expect(log).toContain("MCP catalogue: tools=13 prompts=4 resourceTemplates=4 (read-only deployment)");
    expect(lines.find((line) => line.includes('did not expose "renameTitle"'))).toContain("read-only");
    // Published with nothing an agent can pick it by, which is a broken tool rather than an untidy one. These
    // signals carry no dictionary at all, so every entry is named — including the generated ones, whose only
    // possible text is the model's own `.desc()`.
    expect(lines.find((line) => line.includes('exposed "echoTitle" with no description'))).toContain(
      "no dictionary `.desc()`",
    );
    expect(lines.find((line) => line.includes('exposed "serverResolverTestItemList" with no description'))).toContain(
      "`serverResolverTestItem` has no `.desc()`",
    );
    // A read kept out for declaring no guards is named too, and the sentence is the one an author can act on: the
    // slice call's `get: Public` reaches base CRUD and the root slice and never a named slice, which is how an
    // endpoint arrives here without anyone writing anything down.
    expect(lines.find((line) => line.includes('did not expose "hiddenTitle"'))).toContain("declares no guards");
    // The root list took `root: Public`, and `echoTitle` wrote `[Public]` itself: both are decisions, both quiet.
    expect(lines.find((line) => line.includes('exposed "serverResolverTestItemList", which'))).toBeUndefined();
    expect(lines.find((line) => line.includes('exposed "echoTitle", which'))).toBeUndefined();
  });

  test("refuses a guarded call without naming the guard that refused it", async () => {
    // The framework's own message is `Access denied by guard: None` — the private authorization structure told to
    // the one caller not allowed to see it, which is what the shared "unknown tool" message keeps off the wire.
    // A credential was presented, so this is a tool error rather than a 401 challenge.
    const routes = mcpRoutes();
    const res = await routes["/mcp"].POST(
      new Request("http://127.0.0.1:8080/mcp", {
        method: "POST",
        body: JSON.stringify({ jsonrpc: "2.0", id: 1, method: "tools/call", params: { name: "deniedTitle" } }),
        headers: { "content-type": "application/json", authorization: "Bearer whatever" },
      }),
    );
    const json = (await res.json()) as { result: { isError: boolean; content: { text: string }[] } };
    expect(json.result.isError).toBe(true);
    expect(json.result.content[0].text).toBe("You are not permitted to perform this action.");
  });

  test("refuses a tool the guards kept out, without confirming it exists", async () => {
    const json = await call("hiddenTitle", { id: "507f1f77bcf86cd799439011" });
    expect(json.error.code).toBe(-32602);
    expect(json.error.message).toBe("Unknown tool: hiddenTitle.");
  });

  test("names the argument a caller got wrong instead of reporting a server failure", async () => {
    // Both of these are one keystroke away for a model, and both used to answer "the server failed" — a lie that
    // also wrote a stack to the server log on every attempt.
    const missing = await call("echoTitle");
    expect(missing.result.isError).toBe(true);
    expect(missing.result.content[0].text).toBe('Missing required argument "id".');
    const invalid = await call("echoTitle", { id: 12345 });
    expect(invalid.result.isError).toBe(true);
    expect(invalid.result.content[0].text).toBe('Invalid argument "id": expected ID.');
  });

  test("says a document is missing rather than that the server failed", async () => {
    const uri = "akan://serverResolverTestItem/507f1f77bcf86cd799439011";
    const { json } = await post({ jsonrpc: "2.0", id: 1, method: "resources/read", params: { uri } });
    // An `invalid params` whose message reads "the server failed to complete this request" contradicts itself,
    // and tells an agent holding a stale id nothing it can act on. The framework's own wording is not that
    // message either: `No Document (x): <id>` is a shape internal callers match on, and echoing the id back
    // says nothing the caller did not just send.
    expect(json.error.code).toBe(-32602);
    expect(json.error.message).toBe("No serverResolverTestItem found for the arguments given.");
  });

  test("refuses an argument nobody declared instead of dropping it", async () => {
    // `additionalProperties: false` is published, but this server does not validate against it and plenty of
    // clients do not either — so an extra name was read by nobody. `{ category, status }` on a slice that filters
    // by category alone came back a successful, unfiltered list, which a model reads as its filter having applied.
    const dropped = await call("serverResolverTestItemListInCategory", { category: "all", status: "active" });
    expect(dropped.result.isError).toBe(true);
    expect(dropped.result.content[0].text).toBe('Unknown argument "status".');
    // The framework's own pagination args are declared and stay callable.
    expect((await call("serverResolverTestItemListInCategory", { category: "all", limit: 5 })).result.isError).toBe(
      false,
    );
  });

  test("refuses a value sent for the Any argument it left out of the schema", async () => {
    // The root list names a filter through `queryKey` and passes that filter's own args through `args`, which is
    // `Any` and so published nowhere: an `Any` schema tells a model nothing. A model may still pick a filter that
    // needs no arguments, which is the narrowing the key exists to make deliberate.
    const raw = await call("serverResolverTestItemList", { args: ["all"] });
    expect(raw.result.isError).toBe(true);
    expect(raw.result.content[0].text).toBe('Unknown argument "args".');
    expect((await call("serverResolverTestItemList", { queryKey: "any" })).result.isError).toBe(false);
  });

  test("lifts a lone value into the list an argument was declared as", async () => {
    // A model types a bare string for an array argument, and form-style uri expansion writes one `?tags=` for a
    // single tag. The http path never meets this because `searchParams.getAll` is always an array.
    expect((await call("joinTags", { tags: "solo" })).result.content[0].text).toBe("solo");
    expect((await call("joinTags", { tags: ["a", "b"] })).result.content[0].text).toBe("a|b");
  });

  test("reports an unexpected failure without leaking its message or stack", async () => {
    const json = await call("failingTitle");
    expect(json.result.isError).toBe(true);
    expect(json.result.content[0].text).toBe("The server failed to complete this request.");
    expect(JSON.stringify(json)).not.toContain("boom");
  });

  test("reads a resource through the same path as its tool", async () => {
    const { json } = await post({
      jsonrpc: "2.0",
      id: 1,
      method: "resources/read",
      params: { uri: "akan://serverResolverTestItem/list/inCategory?category=all" },
    });
    expect(json.result.contents[0]).toEqual({
      uri: "akan://serverResolverTestItem/list/inCategory?category=all",
      mimeType: "application/json",
      text: '{"items":[]}',
    });
  });

  test("lists prompts with their arguments and never as tools", async () => {
    const { json } = await post({ jsonrpc: "2.0", id: 1, method: "prompts/list" });
    expect(json.result.prompts.map((prompt: { name: string }) => prompt.name)).toEqual([
      "briefItem",
      "brokenItem",
      "reviewItem",
    ]);
    expect(json.result.prompts.find((p: { name: string }) => p.name === "reviewItem").arguments).toEqual([
      { name: "id", required: true },
      { name: "tone", required: false },
    ]);
  });

  test("runs a prompt through the signal pipeline and returns its messages", async () => {
    const { json } = await post({
      jsonrpc: "2.0",
      id: 1,
      method: "prompts/get",
      params: { name: "reviewItem", arguments: { id: "507f1f77bcf86cd799439011", tone: "blunt" } },
    });
    expect(json.result.messages).toEqual([
      { role: "user", content: { type: "text", text: "Review 507f1f77bcf86cd799439011 in a blunt tone." } },
      // `name` is required by the spec — `ResourceLink` extends `BaseMetadata` — and a client SDK parses this
      // reply against a union a nameless block matches no member of, so leaving it off threw on the client.
      {
        role: "user",
        content: {
          type: "resource_link",
          uri: "akan://item/507f1f77bcf86cd799439011",
          name: "507f1f77bcf86cd799439011",
        },
      },
    ]);
  });

  test("wraps a bare string return into one user message", async () => {
    const { json } = await post({ jsonrpc: "2.0", id: 1, method: "prompts/get", params: { name: "briefItem" } });
    expect(json.result.messages).toEqual([
      { role: "user", content: { type: "text", text: "Answer in three sentences." } },
    ]);
  });

  test("leaves a visual field out of what an agent is handed, and in what the page is", async () => {
    const json = await call("visualItem");
    expect(json.result.structuredContent).toMatchObject({ id: "507f1f77bcf86cd799439011", title: "shot" });
    expect("preview" in json.result.structuredContent).toBe(false);
    expect(json.result.content[0].text).not.toContain("base64");
    // The point of a `visual` field is that a browser still receives it — stripping it in `resolveReturn` would
    // have taken it off the page too, which is why the strip lives in the MCP dispatcher instead.
    const routes = httpRoutes as Record<string, { GET: (req: Request) => Promise<Response> }>;
    const response = await routes["/serverResolverTestItem/visualItem"].GET(
      new Request("http://127.0.0.1:8080/api/serverResolverTestItem/visualItem"),
    );
    expect(await response.json()).toMatchObject({ title: "shot", preview: "data:image/png;base64,AAAA" });
  });

  test("compiles the root list's queryKey and args into the filter the model declared", async () => {
    const routes = httpRoutes as Record<string, { GET: (req: Request) => Promise<Response> }>;
    const list = async (search: string) =>
      await routes["/serverResolverTestItem/serverResolverTestItemList"].GET(
        new Request(`http://127.0.0.1:8080/api/serverResolverTestItem/serverResolverTestItemList${search}`),
      );

    // `args` rides the query string JSON-encoded, which is the only spelling `Any` has there.
    const named = await list(`?queryKey=inCategory&args=${encodeURIComponent('["news"]')}&limit=5`);
    expect(named.status).toBe(200);
    // No key at all is the `any` filter every model carries.
    expect((await list("?limit=5")).status).toBe(200);
    // A filter arg the caller left out is refused rather than widening the query to every row, and a refusal
    // the caller can fix answers 400 — only a throw from inside the filter itself is the app's own 500.
    expect((await list("?queryKey=inCategory")).status).toBe(400);
    expect((await list("?queryKey=notAFilter")).status).toBe(400);
    expect((await list("?queryKey=inCategory&args=not-json")).status).toBe(400);
  });

  test("stops sending the structured result twice when the legacy text block is turned off", async () => {
    const body = { jsonrpc: "2.0", id: 1, method: "tools/call", params: { name: "visualItem", arguments: {} } };
    // The default duplicates on purpose — that is what the spec asks of a server for clients predating
    // `structuredContent` — and it is also a flat doubling of what every model-returning tool costs.
    const { json: both } = await postWith(body, {});
    expect(JSON.parse(both.result.content[0].text)).toEqual(both.result.structuredContent);
    const { json: once } = await postWith(body, { legacyTextBlock: false });
    expect(once.result.structuredContent).toMatchObject({ id: "507f1f77bcf86cd799439011", title: "shot" });
    expect(once.result.content[0].text).toBe("The result is in this call's structuredContent.");
  });

  test("keeps the text block whole for a scalar return, which has no structured half to point at", async () => {
    const body = {
      jsonrpc: "2.0",
      id: 1,
      method: "tools/call",
      params: { name: "echoTitle", arguments: { id: "507f1f77bcf86cd799439011", suffix: "tail" } },
    };
    const { json } = await postWith(body, { legacyTextBlock: false });
    expect(json.result.content[0].text).toBe("507f1f77bcf86cd799439011:tail");
  });

  test("returns the same messages over the plain HTTP route", async () => {
    // That route exists so a web UI can preview a prompt, and it is only a preview if both transports produce
    // the same thing. A prompt rides the `Any` carrier, so normalizing in the MCP dispatcher alone would leave
    // the HTTP route handing back whatever `exec` happened to return — here, a bare string.
    const routes = httpRoutes as Record<string, { GET: (req: Request) => Promise<Response> }>;
    const response = await routes["/serverResolverTestItem/briefItem"].GET(
      new Request("http://127.0.0.1:8080/api/serverResolverTestItem/briefItem"),
    );
    expect(await response.json()).toEqual([
      { role: "user", content: { type: "text", text: "Answer in three sentences." } },
    ]);
  });

  test("refuses a prompt call that omits a required argument", async () => {
    // Caught against the published catalogue: an absent value would otherwise deserialize to an empty string
    // and reach the endpoint as if the caller had sent one.
    const { json } = await post({ jsonrpc: "2.0", id: 1, method: "prompts/get", params: { name: "reviewItem" } });
    expect(json.error.code).toBe(-32602);
    expect(json.error.message).toBe("Missing prompt arguments: id.");
  });

  test("names a bad prompt argument instead of reporting an internal error", async () => {
    // A prompt has no `isError` result, so the code is the only place left to say whose mistake it was — and the
    // *missing*-argument check right above answers -32602 for what is the same class of caller error.
    const { json } = await post({
      jsonrpc: "2.0",
      id: 1,
      method: "prompts/get",
      params: { name: "reviewItem", arguments: { id: "not-an-id" } },
    });
    expect(json.error.code).toBe(-32602);
    expect(json.error.message).toBe('Invalid argument "id": expected ID.');
  });

  test("rejects a malformed message set instead of passing it through", async () => {
    const { json } = await post({ jsonrpc: "2.0", id: 1, method: "prompts/get", params: { name: "brokenItem" } });
    expect(json.error.code).toBe(-32603);
    expect(json.result).toBeUndefined();
  });

  test("walks the catalogue a page at a time and stops without a cursor", async () => {
    const names: string[] = [];
    let cursor: string | undefined;
    do {
      const { json } = await postPaged(
        { jsonrpc: "2.0", id: 1, method: "tools/list", ...(cursor ? { params: { cursor } } : {}) },
        3,
      );
      names.push(...json.result.tools.map((tool: { name: string }) => tool.name));
      cursor = json.result.nextCursor;
    } while (cursor);
    const { json } = await post({ jsonrpc: "2.0", id: 1, method: "tools/list" });
    expect(names).toEqual(json.result.tools.map((tool: { name: string }) => tool.name));
    // One page holds the whole catalogue here, so there is nothing left to point at.
    expect(json.result.nextCursor).toBeUndefined();
  });

  test("refuses a cursor that addresses nothing rather than serving a short page", async () => {
    const { json } = await post({
      jsonrpc: "2.0",
      id: 1,
      method: "tools/list",
      params: { cursor: Buffer.from("999").toString("base64url") },
    });
    expect(json.error.code).toBe(-32602);
    expect(json.error.message).toBe("Invalid cursor.");
  });

  test("refuses a cursor that decodes to nothing instead of restarting the walk", async () => {
    // `Number("")` is 0, so an empty cursor would read as "start from the beginning" and hand a client that
    // corrupted its cursor page one again, forever.
    for (const cursor of ["", "===="]) {
      const { json } = await post({ jsonrpc: "2.0", id: 1, method: "tools/list", params: { cursor } });
      expect(json.error?.message).toBe("Invalid cursor.");
    }
  });

  test("tells a modern client how long a catalogue may be cached, and per whom", async () => {
    const meta = {
      "io.modelcontextprotocol/protocolVersion": "2026-07-28",
      "io.modelcontextprotocol/clientCapabilities": {},
    };
    // The modern era mirrors the version and the method into headers on every POST, and one that omits either
    // is refused — a gateway rule keyed on a header does not fire for a request that left the header out.
    const modern = async (method: string) =>
      await (
        await postRaw(
          { jsonrpc: "2.0", id: 1, method, params: { _meta: meta } },
          { "mcp-method": method, "mcp-protocol-version": "2026-07-28" },
        )
      ).json();
    const json = await modern("tools/list");
    // Private because `filterForAccount` makes the listing depend on the caller's credential.
    expect(json.result.cacheScope).toBe("private");
    expect(json.result.ttlMs).toBe(300_000);
    const discover = await modern("server/discover");
    expect(discover.result.cacheScope).toBe("public");
    const legacy = await post({ jsonrpc: "2.0", id: 1, method: "tools/list" });
    expect(legacy.json.result.cacheScope).toBeUndefined();
  });

  test("streams progress and then the result when the caller asks for both", async () => {
    const res = await postRaw(
      {
        jsonrpc: "2.0",
        id: 7,
        method: "tools/call",
        params: { name: "slowTitle", arguments: {}, _meta: { progressToken: "tok-1" } },
      },
      { accept: "application/json, text/event-stream" },
    );
    expect(res.headers.get("content-type")).toBe("text/event-stream");
    // An intermediary that buffers the stream would deliver every event only once the work already finished.
    expect(res.headers.get("x-accel-buffering")).toBe("no");
    const messages = (await res.text())
      .split("\n\n")
      .flatMap((frame) => (frame.startsWith("data: ") ? [JSON.parse(frame.slice(6))] : []));
    expect(messages.map((message) => message.method ?? "result")).toEqual([
      "notifications/progress",
      "notifications/progress",
      "result",
    ]);
    expect(messages[0].params).toEqual({ progressToken: "tok-1", progress: 1, total: 2, message: "counting" });
    expect(messages[1].params).toEqual({ progressToken: "tok-1", progress: 2, total: 2 });
    // The final message is the ordinary JSON-RPC response — a streamed call answers nothing extra.
    expect(messages[2]).toMatchObject({ jsonrpc: "2.0", id: 7, result: { isError: false } });
    expect(messages[2].result.content[0].text).toBe("counted");
  });

  test("answers with plain JSON unless the caller asks for a stream and names a token", async () => {
    const call = { jsonrpc: "2.0", id: 1, method: "tools/call", params: { name: "slowTitle", arguments: {} } };
    // A token with no stream to carry it, and a stream with no token to correlate against, are both just a call.
    const tokenOnly = await postRaw({ ...call, params: { ...call.params, _meta: { progressToken: "t" } } }, {});
    expect(tokenOnly.headers.get("content-type")).toContain("application/json");
    const streamOnly = await postRaw(call, { accept: "text/event-stream" });
    expect(streamOnly.headers.get("content-type")).toContain("application/json");
    expect((await streamOnly.json()).result.content[0].text).toBe("counted");
  });

  test("keeps the 401 challenge reachable by deciding to stream only after guards pass", async () => {
    // `None` refuses before the endpoint body could report anything, so the response is still a plain status.
    const res = await postRaw(
      {
        jsonrpc: "2.0",
        id: 1,
        method: "tools/call",
        params: { name: "deniedTitle", arguments: {}, _meta: { progressToken: "t" } },
      },
      { accept: "text/event-stream" },
    );
    expect(res.status).toBe(401);
    expect(res.headers.get("WWW-Authenticate")).toContain("resource_metadata=");
  });

  test("lets a configured browser origin past the preflight and reads its own answer", async () => {
    // `allowedOrigins` grants a browser-hosted client nothing on its own: `content-type: application/json` and
    // the `mcp-*` mirror headers each force a preflight, and an answer with no `access-control-allow-origin` is
    // unreadable to the page that asked for it.
    const routes = mcpRoutes({ allowedOrigins: ["https://console.example.com"] });
    const headers = { origin: "https://console.example.com" };
    const preflight = await routes["/mcp"].OPTIONS(
      new Request("http://127.0.0.1:8080/mcp", {
        method: "OPTIONS",
        headers: { ...headers, "access-control-request-headers": "authorization, mcp-method" },
      }),
    );
    expect(preflight.status).toBe(204);
    expect(preflight.headers.get("access-control-allow-origin")).toBe("https://console.example.com");
    expect(preflight.headers.get("access-control-allow-headers")).toBe("authorization, mcp-method");
    const res = await routes["/mcp"].POST(
      new Request("http://127.0.0.1:8080/mcp", {
        method: "POST",
        body: JSON.stringify({ jsonrpc: "2.0", id: 1, method: "tools/list" }),
        headers: { "content-type": "application/json", ...headers },
      }),
    );
    expect(res.headers.get("access-control-allow-origin")).toBe("https://console.example.com");
    expect(res.headers.get("vary")).toBe("origin");
    const refused = await routes["/mcp"].OPTIONS(
      new Request("http://127.0.0.1:8080/mcp", { method: "OPTIONS", headers: { origin: "https://evil.example.com" } }),
    );
    expect(refused.status).toBe(403);
  });

  test("lets a browser read the 405 for a verb this transport does not have", async () => {
    // Legacy clients probe `GET /mcp` for a server-opened stream. Without the CORS header the browser hands the
    // page an unlabelled network error, which is indistinguishable from the server being unreachable.
    const routes = mcpRoutes({ allowedOrigins: ["https://console.example.com"] });
    const headers = { origin: "https://console.example.com" };
    for (const method of ["GET", "DELETE"] as const) {
      const res = await routes["/mcp"][method](new Request("http://127.0.0.1:8080/mcp", { method, headers }));
      expect(res.status).toBe(405);
      expect(res.headers.get("access-control-allow-origin")).toBe("https://console.example.com");
    }
  });

  test("matches an Origin against the public host rather than the one the proxy dialed", async () => {
    // The same mismatch the resource identifier had: behind the gateway `req.url` names the internal child, so a
    // browser client whose `Origin` is the public URL is refused on every request.
    const proxied = (headers: Record<string, string>) =>
      mcpRoutes()["/mcp"].POST(
        new Request("http://akan-child:9001/mcp", {
          method: "POST",
          body: JSON.stringify({ jsonrpc: "2.0", id: 1, method: "tools/list" }),
          headers: { "content-type": "application/json", origin: "https://app.example.com", ...headers },
        }),
      );
    const forwarded = await proxied({ "x-forwarded-host": "app.example.com", "x-forwarded-proto": "https" });
    expect(forwarded.status).toBe(200);
    expect(forwarded.headers.get("access-control-allow-origin")).toBe("https://app.example.com");
    // Without the forwarded headers the origin really is a stranger, and the rebinding defence still holds.
    expect((await proxied({})).status).toBe(403);
  });

  test("advertises the templates its exposed reads are addressable by", async () => {
    const { json } = await post({ jsonrpc: "2.0", id: 1, method: "resources/templates/list" });
    expect(json.result.resourceTemplates.map((t: { uriTemplate: string }) => t.uriTemplate)).toEqual([
      "akan://serverResolverTestItem/light/{serverResolverTestItemId}",
      "akan://serverResolverTestItem/{serverResolverTestItemId}",
      "akan://serverResolverTestItem/list{?queryKey,skip,limit,sort}",
      "akan://serverResolverTestItem/list/inCategory{?category,skip,limit,sort}",
    ]);
  });
});
